name: Release
on:
  push:
    branches:
      - master

jobs:
  test-action:
    uses: ./.github/workflows/test_action.yml
  release:
    permissions:
      contents: write #  to be able to publish a GitHub release
      issues: write #  to be able to comment on released issues
      pull-requests: write #  to be able to comment on released pull requests

    needs: test-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx -s -p semantic-release-major-tag -p semantic-release semantic-release
